fix: only show new versions of spaces if they are newer than the local copies
blankdotspace/space-system pull request #249
Opened 2024-07-11 22:03 UTC by hiporox

2024-07-11 22:25 UTC, ryannorton requested changes

2024-07-11 22:25 UTC, ryannorton commented on src/common/data/stores/app/homebase/homebaseStore.ts
> +        spaceConfig.timestamp &&
Handle undefined `spaceConfig`/`currentHomebase`

2024-07-11 22:25 UTC, ryannorton commented on src/common/data/stores/app/space/spaceStore.ts
> +        spaceConfig &&
Handle undefined `spaceConfig`/`currentLocalCopy`

2024-07-11 22:39 UTC, ryannorton commented on src/common/data/stores/app/homebase/homebaseStore.ts
> +        currentHomebase.timestamp &&
Should also return here if local config has a timestamp and the fetched one doesn't

2024-07-11 22:43 UTC, ryannorton commented on src/common/data/stores/app/space/spaceStore.ts
> +        spaceConfig.timestamp &&
Should also return true if local config has a timestamp and the fetched one doesn't

2024-07-12 20:21 UTC, hiporox commented
@ryannorton Fixed comments

2024-07-28 22:43 UTC, merged