Feat/channel fidget
blankdotspace/space-system pull request #33
Opened 2024-05-07 19:23 UTC by gitpancake

This is a channel fidget!

Two hooks - get channel info / get channel casts
Limit: 20 casts per feed 
Enter channel ID, the feed fetches all information and displays image / text content in a feed

WIP:

Lazy loading on scroll
Clean up CSS

Wallet address (base): 0x412B59e147aF4513c2EA537cE5036c357f2A44a7
Wallet address (mainnet): 0xaa3c0FAa24E67eBe9B73Fe3efaf9D06F9Ba57622

Thanks!

2024-05-07 20:37 UTC, hiporox commented
@gitpancake This is awesome. Thank you for your contribution! 

I have updated the base branch so that I can better compare the changes you made to @j-paterson `LayoutSystem` changes. I will add some reviews to this PR shortly

2024-05-07 20:43 UTC, hiporox requested changes
Two major things beyond the little comments:

1. You have placed all of your code into the `src/fidgets/example/index.tsx` and created a new file `src/fidgets/channel/index.tsx` that has the old content of `src/fidgets/example/index.tsx`. Please change this so that all of your code is in the new file `src/fidgets/channel/index.tsx` and leave the example file alone

2. You have a bunch of lint changes that are applied to `src/pages/homebase/index.tsx`. Please remove these from the PR. I am happy to discuss the lint style settings, but that should be reserved for a different PR

2024-05-07 20:43 UTC, hiporox commented on .gitignore
> +.env**
Please remove this. `.env` files should be included, following the Next.js spec for local vs. share variables: https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables

We already include the following lower on in the the `.gitignore`:
```
# dotenv environment variables file
.env.*.local
.env.test
.env.local
```

2024-05-07 20:43 UTC, hiporox commented on README.md
> +https://docs.nounspace.com/nounspace-alpha/
Great, thank you!

2024-05-07 20:43 UTC, hiporox commented on src/common/ui/templates/space/index.tsx
> +import { ReactElement } from "react";
`React` needs to be imported into all `.tsx` files

2024-05-07 20:43 UTC, hiporox commented on src/common/ui/templates/space/index.tsx
> +        {/* <div key={0} data-grid={config.fidgetConfigs[0]} className="overflow-hidden rounded-md flex justify-center items-center">
Why did this get commented out?

2024-05-07 20:43 UTC, hiporox commented on src/common/ui/templates/space/index.tsx
> +    };
Thank you for making is correct Typescript declarations

2024-05-07 22:32 UTC, hiporox commented
@gitpancake I have rebased your changes into the [feat/channel-fidget](https://github.com/Nounspace/nounspace.ts/tree/feat/channel-fidget) branch. Feel free to cherry pick/copy from there to resolve merge conflicts that now exist

2024-05-08 17:35 UTC, closed without merging

2024-05-13 21:35 UTC, gitpancake commented
Hey @hiporox  thank you for the review! I will review and make changes this week

2024-05-13 21:42 UTC, hiporox commented
Sounds good. I know we did a pretty massive overhaul of the system since you last looked at it. Let me know if you need help porting to system