feat: add table fidget
blankdotspace/space-system pull request #415
Opened 2024-09-10 11:16 UTC by r4topunk

This PR adds a table fidget that parses CSVs and displays them as tables.

The tables are fully customizable and it's possible to use data from text, file and url.

The text and file are the same input, as far as the file button just opens a file and puts it's contents into the text input. And the url is loaded as soon as the fidget is loaded.

Obs: I loved the experience of developing fidgets, it's so cool to think about the possibilities of creations. I have always argued that the web should be modular, and this is how Nounspace works!

2024-09-10 20:05 UTC, sktbrd commented
Looks Perfect to me !

2024-09-20 20:19 UTC, sktbrd commented
@j-paterson I think that one scaped the merge wars

2024-12-20 20:11 UTC, j-paterson requested changes
This PR has too many additional changes beyond the table fidget. Please isolate the table fidget work and create separate PRs if the other items are needed.

2024-12-21 12:30 UTC, r4topunk commented
@j-paterson what happened with this pr? why there are so many commits after my last changes on the table fidget???

2025-01-07 00:11 UTC, j-paterson commented
> @j-paterson what happened with this pr? why there are so many commits after my last changes on the table fidget???

This is just a victim to a force push we had a while back. Try just rebasing it and force pushing.

2025-02-12 20:18 UTC, sktbrd commented
That one got rolled over as well.

2025-04-09 01:21 UTC, sktbrd commented
what to do with that ? may be we close @willyogo ?

2025-04-09 12:06 UTC, r4topunk commented
> what to do with that ? may be we close @willyogo ?

@sktbrd 
I think we should try to clean up the rebase to try to merge again...

2025-04-09 15:16 UTC, willyogo commented
> > what to do with that ? may be we close @willyogo ?
> 
> @sktbrd I think we should try to clean up the rebase to try to merge again...

Good q. My gut says let's leave it for now and then consider bringing it back when we revamp the fidget selection UX in the context of Frame v2

2025-04-14 22:18 UTC, closed without merging