fix: add ref to control player url
blankdotspace/space-system pull request #521
Opened 2024-12-11 17:44 UTC by r4topunk

2025-01-09 22:02 UTC, j-paterson requested changes

2025-01-09 22:02 UTC, j-paterson commented on src/common/components/organisms/Player.tsx
> +  const latestUrlRef = useRef<string | string[]>(url);
Why are we using a Ref for this instead of a State variable

2025-01-17 17:24 UTC, sktbrd commented
Can we close this one @r4topunk @j-paterson ?

2025-02-12 20:17 UTC, sktbrd commented
@r4topunk can you close this one and do it again after the app migration , if still needed?

2025-03-28 17:59 UTC, closed without merging